steps:
  - block: "Test Benchmark Builds"
    prompt: "Select machines where you want to run a test build"
    fields:
      - select: "Machines"
        key: "machines"
        required: true
        multiple: true
        options:
          - label: "ursa-i9-9960x"
            value: "ursa-i9-9960x"
          - label: "ursa-thinkcentre-m75q"
            value: "ursa-thinkcentre-m75q"
          - label: "ec2-t3-xlarge-us-east-2"
            value: "ec2-t3-xlarge-us-east-2"
          - label: "test-mac-arm"
            value: "test-mac-arm"
          - label: "voltron-pavilion"
            value: "voltron-pavilion"

  - label: "Test Benchmark Builds"
    command: |
      echo "$(buildkite-agent meta-data get machines)"
      docker run -it \
        -e MACHINES="$(buildkite-agent meta-data get machines)" \
        -e BUILDKITE_API_BASE_URL=${BUILDKITE_API_BASE_URL} \
        -e BUILDKITE_ORG=${BUILDKITE_ORG} \
        -e BUILDKITE_API_TOKEN=${BUILDKITE_API_TOKEN} \
        -e BRANCH=${BUILDKITE_BRANCH} \
        -e COMMIT=${BUILDKITE_COMMIT} \
        -e MESSAGE=${BUILDKITE_MESSAGE} \
        $(docker build -q .) python -m buildkite.benchmark-test.run_test_builds
    agents:
      queue: "arrow-bci"
