steps:
  - label: "Build Arrow-BCI API Service Docker Image"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - docker-compose -f envs/prod/docker-compose.yml down
      - docker-compose -f envs/prod/docker-compose.yml build

  - wait

  - label: "Run benchalerts pipelines"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - docker-compose -f envs/prod/docker-compose.yml run app python -m buildkite.schedule_and_publish.run_benchalerts
